In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(616)
rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [4]:
rng.integers(0, 10, 100)

array([9, 8, 7, 5, 0, 5, 6, 9, 2, 1, 1, 6, 8, 4, 7, 5, 8, 2, 8, 3, 3, 9,
       6, 0, 1, 3, 1, 7, 5, 3, 7, 2, 2, 4, 0, 7, 1, 1, 0, 6, 1, 2, 8, 7,
       4, 6, 2, 3, 3, 0, 2, 2, 4, 8, 0, 0, 4, 5, 8, 6, 8, 1, 3, 5, 5, 5,
       7, 0, 0, 6, 9, 9, 0, 8, 5, 3, 3, 6, 2, 6, 1, 3, 8, 6, 3, 2, 2, 5,
       2, 6, 9, 2, 5, 0, 6, 1, 3, 1, 9, 4], dtype=int64)

In [5]:
rng.normal(50, 5, 10)

array([46.93674729, 59.54526862, 53.43774821, 48.43637794, 46.85678879,
       41.4561919 , 56.48790756, 53.94354469, 54.60078538, 48.61302076])