In [1]:
import numpy as np

In [3]:
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
integer_array[2]

2

In [6]:
integer_array[-1]

11

In [7]:
integer_array[-2]

10

In [9]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [10]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [12]:
new_array = integer_array.reshape(3, 4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
new_array[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
new_array[2, :]

array([ 8,  9, 10, 11])

In [16]:
new_array[:, 3]

array([ 3,  7, 11])

In [18]:
new_array[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [19]:
new_array[2, 1]

9