In [1]:
import numpy as np

rng = np.random.default_rng(616)

inventory = rng.integers(0, 100, 10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [2]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [3]:
(inventory / 2).dtype

dtype('float64')

In [5]:
price = (rng.random(11) * 10).round(2)

price

array([5.24, 8.02, 0.75, 1.51, 8.97, 6.63, 7.26, 7.66, 0.3 , 7.78, 9.62])

In [6]:
price * inventory

ValueError: operands could not be broadcast together with shapes (11,) (10,) 

In [7]:
price = (rng.random(10) * 10).round(2)

price * inventory

array([ 74.1 ,  65.91, 440.82, 509.12, 204.  , 378.12, 182.4 ,   6.6 ,
       108.02, 313.5 ])

In [8]:
inventory_list = list(inventory)
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [9]:
inventory_list + 2

TypeError: can only concatenate list (not "int") to list

In [10]:
new_inventory = []

for x in inventory_list:
    new_inventory.append(x + 2)
    
new_inventory

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [11]:
[x + 2 for x in inventory_list]

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]